---

require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  Exclude:
    - 'bin/**'
    - 'config/**'
    - 'config/**/*'
    - 'db/schema.rb'
    - 'db/migrate/**'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
  NewCops: enable

Style/ClassAndModuleChildren:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
  SafeAutoCorrect: true

Style/IfUnlessModifier:
  Enabled: false

Layout/LineLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Enabled: false